# Generated by Django 5.0.6 on 2024-07-01 16:31

import datetime
import reservations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(default=datetime.date.today, validators=[reservations.models.validate_reservation_date]),
        ),
    ]
